In [4]:
import pandas as pd
#hh_data = pd.read_csv('data/hh_data_w.csv')
hh_data = pd.read_csv('data/hh_data_w.csv', sep=';')  # Например, для разделителя ";"
hh_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Пол, возраст                     44744 non-null  object
 1   ЗП                               44744 non-null  object
 2   Ищет работу на должность:        44744 non-null  object
 3   Город, переезд, командировки     44744 non-null  object
 4   Занятость                        44744 non-null  object
 5   График                           44744 non-null  object
 6   Опыт работы                      44576 non-null  object
 7   Последнее/нынешнее место работы  44587 non-null  object
 8   Последняя/нынешняя должность     44586 non-null  object
 9   Образование и ВУЗ                44588 non-null  object
 10  Обновление резюме                44588 non-null  object
 11  Авто                             44588 non-null  object
dtypes: object(12)
memory usage: 4.1+ MB

In [5]:
#Чему равна размерность таблицы? Введите её в виде кортежа (число строк, число столбцов).
hh_data.shape

(44744, 12)

In [6]:
hh_data.head()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 8:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 8:35,Не указано
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано

In [7]:
hh_data.tail()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
44739,"Мужчина , 30 лет , родился 17 января 1989",50000 руб.,"Финансист, аналитик, экономист, бухгалтер, мен...","Тверь , готов к переезду (Москва, Химки) , гот...",полная занятость,"полный день, удаленная работа","Опыт работы 7 лет 7 месяцев Финансист, аналит...","ООО ""IAS"" (независимый участник объединения Ru...",Руководитель субгруппы,Высшее образование 2015 Московский гуманитарн...,22.04.2019 12:32,Не указано
44740,"Мужчина , 27 лет , родился 5 марта 1992",39000 руб.,"Системный администратор, IT-специалист","Липецк , готов к переезду , готов к командировкам","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день, ...","Опыт работы 7 лет Системный администратор, IT...",ИП Пестрецов,Предприниматель,Высшее образование (Бакалавр) 2016 Воронежски...,22.04.2019 13:11,Не указано
44741,"Женщина , 48 лет , родилась 26 декабря 1970",40000 руб.,"Аналитик данных, Математик","Челябинск , готова к переезду , готова к редки...",полная занятость,"полный день, удаленная работа",Опыт работы 21 год 5 месяцев Январь 1998 — по...,"ОАО «ЧМК», Исследовательско-Технологический Це...",Начальник группы аналитики,Высшее образование 2000 Южно-Уральский госуда...,09.04.2019 5:07,Не указано
44742,"Мужчина , 24 года , родился 6 октября 1994",20000 руб.,Контент-менеджер,"Тамбов , не готов к переезду , не готов к кома...","частичная занятость, полная занятость",удаленная работа,Опыт работы 3 года 10 месяцев Контент-менедже...,IQ-Maxima,Менеджер проектов,Высшее образование 2015 Тамбовский государств...,26.04.2019 14:25,Имеется собственный автомобиль
44743,"Мужчина , 38 лет , родился 25 апреля 1980",120000 руб.,Руководитель проекта,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 15 лет 10 месяцев Руководитель пр...,ПАО ГК ТНС энерго,Руководитель отдела технической поддержки,Высшее образование 1997 Южно-Российский госуд...,05.07.2018 20:15,Не указано

In [8]:
# Подсчёт количества уникальных значений в столбце «Опыт работы»
hh_data['Опыт работы'].nunique()

44413

In [9]:
# Находим самую распространённую должность
hh_data['Ищет работу на должность:'].value_counts().idxmax()

'Системный администратор'

Начнём с простого — с признака «Образование и ВУЗ». Его текущий формат — это: <Уровень образования год выпуска ВУЗ специальность...>. Например:

Высшее образование 2016 Московский авиационный институт (Национальный исследовательский университет)
Неоконченное высшее образование 2000 Балтийская государственная академия рыбопромыслового флота
Нас будет интересовать только уровень образования. Причём, для простоты мы будем считать, что соискатель указывает свой максимальный уровень образования в первых трёх словах столбца «Образование и ВУЗ».

Создайте с помощью функции-преобразования новый признак «Образование», который должен иметь четыре категории: «высшее», «неоконченное высшее», «среднее специальное» и «среднее».

Выполните преобразование, ответьте на контрольные вопросы и удалите признак «Образование и ВУЗ».

In [10]:
# Создаём копию данных
hh_data_copy = hh_data.copy()

# Функция для извлечения уровня образования
def extract_education_level(text):
    # Разделяем текст на слова и берём первые три
    words = text.split()[:3]
    # Объединяем их в строку
    education_level = ' '.join(words)
    
    # Определяем категорию
    if 'высшее' in education_level.lower() and 'неоконченное' not in education_level.lower():
        return 'высшее'
    elif 'неоконченное высшее' in education_level.lower():
        return 'неоконченное высшее'
    elif 'среднее специальное' in education_level.lower():
        return 'среднее специальное'
    elif 'среднее' in education_level.lower():
        return 'среднее'
    else:
        return 'не указано'

# Проверяем пропущенные значения в столбце «Образование и ВУЗ»
print("Количество пропущенных значений:", hh_data_copy['Образование и ВУЗ'].isnull().sum())

# Заменяем пропущенные значения на пустую строку
hh_data_copy['Образование и ВУЗ'] = hh_data_copy['Образование и ВУЗ'].fillna('')

# Применяем функцию к столбцу «Образование и ВУЗ»
hh_data_copy['Образование'] = hh_data_copy['Образование и ВУЗ'].apply(extract_education_level)

# Проверяем уникальные значения нового столбца
print("Уникальные значения в столбце «Образование»:", hh_data_copy['Образование'].unique())

# Удаляем исходный столбец «Образование и ВУЗ»
hh_data_copy.drop(columns=['Образование и ВУЗ'], inplace=True)

# Проверяем результат
hh_data_copy.head()

Количество пропущенных значений: 156
Уникальные значения в столбце «Образование»: ['неоконченное высшее' 'высшее' 'среднее специальное' 'среднее'
 'не указано']

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",12.04.2019 8:42,Не указано,высшее
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,16.04.2019 8:35,Не указано,среднее специальное
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,08.04.2019 14:23,Не указано,высшее
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,22.04.2019 10:32,Не указано,высшее

In [11]:
# Подсчитываем количество соискателей с уровнем образования «среднее»
hh_data_copy[hh_data_copy['Образование'] == 'среднее'].shape[0]

559

Теперь нас интересует столбец «Пол, возраст». Его текущий формат: <Пол , возраст, дата рождения>. Например:

Мужчина , 39 лет , родился 27 ноября 1979
Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец..

In [12]:
# Разделяем столбец «Пол, возраст» на три части
split_data = hh_data_copy['Пол, возраст'].str.split(' , ', expand=True)

# Присваиваем новые столбцы
hh_data_copy['Пол'] = split_data[0]  # Первая часть — пол
hh_data_copy['Возраст'] = split_data[1]  # Вторая часть — возраст
hh_data_copy['Дата_рождения'] = split_data[2]  # Третья часть — дата рождения

# Удаляем исходный столбец «Пол, возраст»
hh_data_copy.drop(columns=['Пол, возраст'], inplace=True)

# Проверяем результат
hh_data_copy.head()

,ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,Дата_рождения
0,29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее,Мужчина,39 лет,родился 27 ноября 1979
1,40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",12.04.2019 8:42,Не указано,высшее,Мужчина,60 лет,родился 20 марта 1959
2,20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,16.04.2019 8:35,Не указано,среднее специальное,Женщина,36 лет,родилась 12 августа 1982
3,100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,08.04.2019 14:23,Не указано,высшее,Мужчина,38 лет,родился 25 июня 1980
4,140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,22.04.2019 10:32,Не указано,высшее,Женщина,26 лет,родилась 3 марта 1993

Сколько процентов женских резюме представлено в наших данных? Ответ округлите до сотых.

In [13]:
female_percentage = round((hh_data_copy[hh_data_copy['Пол'] == 'Женщина'].shape[0] / hh_data_copy.shape[0]) * 100, 2)
print(f"Процент женских резюме: {female_percentage}%")

Процент женских резюме: 19.07%

Чему равен средний возраст соискателей? Ответ округлите до десятых.

In [14]:
# Разделяем строку по пробелу и извлекаем число
hh_data_copy['Возраст_число'] = hh_data_copy['Возраст'].str.split().str[0].astype(float)

# Вычисляем средний возраст и округляем
print(f"Средний возраст соискателей: {round(hh_data_copy['Возраст_число'].mean(),1)} лет")

Средний возраст соискателей: 32.2 лет

Следующим этапом преобразуем признак «Опыт работы». Его текущий формат: <Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>.

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовём «Опыт работы (месяц)».

Для начала обсудим условия решения задачи:

Во-первых, в данном признаке есть пропуски. Условимся, что, если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN).
Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значение Не указано. Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях).

В-четвёртых, у нас есть проблема: опыт работы может быть представлен только в годах или только в месяцах. Например, можно встретить следующие варианты:

Опыт работы 3 года 2 месяца
Опыт работы 4 года
Опыт работы 11 месяцев
Учитывайте эту особенность в вашем коде.

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.

Выполните преобразование и удалите столбец «Опыт работы» из таблицы.

In [15]:
import numpy as np

# Функция для преобразования опыта работы в месяцы
def get_experience(arg):
    # Если значение пропущено или равно "Не указано", возвращаем NaN
    if pd.isna(arg) or arg == 'Не указано':
        return np.nan
    
    # Ключевые слова для поиска лет и месяцев
    year_words = ['год', 'года', 'лет']
    month_words = ['месяц', 'месяца', 'месяцев']
    
    # Разделяем строку на части (первые 7 элементов)
    arg_splitted = arg.split(' ')[:7]
    years = 0
    months = 0
    
    # Проходим по частям строки
    for index, item in enumerate(arg_splitted):
        # Если находим ключевое слово из years_Word извлекаем количество лет
        if item in year_words:
            try:
                years = int(arg_splitted[index - 1]) 
            except (ValueError, IndexError):
                years = 0  # Если не удалось преобразовать, считаем 0
        
        # Если находим ключевое слово из month_words извлекаем количество месяцев
        if item in month_words:
            try:
                months = int(arg_splitted[index - 1])  # Берём предыдущий элемент (число)
            except (ValueError, IndexError):
                months = 0  # Если не удалось преобразовать, считаем 0
    
    # Преобразуем годы в месяцы и суммируем
    return int(years * 12 + months)

# Применяем функцию к столбцу «Опыт работы»
hh_data_copy['Опыт работы (месяц)'] = hh_data_copy['Опыт работы'].apply(get_experience)

# Выводим два столбца для проверки
hh_data_copy[['Опыт работы', 'Опыт работы (месяц)']].head(10)  # Первые 10 строк

# Удаляем исходный столбец «Опыт работы» (если нужно)
# hh_data_copy.drop(columns=['Опыт работы'], inplace=True)

                                         Опыт работы  Опыт работы (месяц)
0  Опыт работы 16 лет 10 месяцев  Август 2010 — п...                202.0
1  Опыт работы 19 лет 5 месяцев  Январь 2000 — по...                233.0
2  Опыт работы 10 лет 3 месяца  Октябрь 2004 — Де...                123.0
3  Опыт работы 18 лет 9 месяцев  Август 2017 — Ап...                225.0
4  Опыт работы 5 лет 7 месяцев  Региональный мене...                 67.0
5  Опыт работы 9 лет 9 месяцев  Технический специ...                117.0
6  Опыт работы 22 года 9 месяцев  Руководитель ИТ...                273.0
7  Опыт работы 3 года 11 месяцев  Декабрь 2016 — ...                 47.0
8  Опыт работы 8 лет 9 месяцев  Декабрь 2016 — по...                105.0
9  Опыт работы 16 лет 6 месяцев  Июнь 2018 — по н...                198.0

In [16]:
# вычисляем медианный опыт работы и округляем
round(hh_data_copy['Опыт работы (месяц)'].median())

100

Хорошо идём! :) Следующий на очереди — признак «Город, переезд, командировки». Информация в нём представлена в следующем виде: <Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>.

В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

Москва , не готов к переезду , готов к командировкам
Москва , м. Беломорская , не готов к переезду, не готов к командировкам
Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам
Создадим отдельные признаки «Город», «Готовность к переезду», «Готовность к командировкам». При этом важно учесть:

⛏ Признак «Город» может содержать только четыре категории: «Москва», «Санкт-Петербург» и «город-миллионник» (их список ниже), остальные обозначьте как «другие».

Список городов-миллионников
Информация о метро, рядом с которым проживает соискатель, нас не интересует.

⛏ Признак «Готовность к переезду» должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке «Город, переезд, командировки». Например:

… , готов к переезду , …
… , не готова к переезду , …
… , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
… , хочу переехать (США) , …
Нас интересует только сам факт возможности/желания переезда.

⛏ Признак «Готовность к командировкам» должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке «Город, переезд, командировки». Например:

… , готов к командировкам , …
… , готова к редким командировкам , …
… , не готов к командировкам , …
Нас интересует только сам факт готовности к командировке.

Ещё один важный момент: при выгрузке данных у некоторых соискателей «потерялась» информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.

Выполните преобразования и удалите столбец «Город, переезд, командировки» из таблицы.

In [17]:
hh_data_copy.head()

,ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,Дата_рождения,Возраст_число,Опыт работы (месяц)
0,29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее,Мужчина,39 лет,родился 27 ноября 1979,39.0,202.0
1,40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",12.04.2019 8:42,Не указано,высшее,Мужчина,60 лет,родился 20 марта 1959,60.0,233.0
2,20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,16.04.2019 8:35,Не указано,среднее специальное,Женщина,36 лет,родилась 12 августа 1982,36.0,123.0
3,100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,08.04.2019 14:23,Не указано,высшее,Мужчина,38 лет,родился 25 июня 1980,38.0,225.0
4,140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,22.04.2019 10:32,Не указано,высшее,Женщина,26 лет,родилась 3 марта 1993,26.0,67.0

In [20]:
def get_city(arg):
    million_cities = ['Новосибирск', 'Екатеринбург', 'Нижний Новгород',
                      'Казань', 'Челябинск', 'Омск', 'Самара', 'Ростов-на-Дону', 
                      'Уфа', 'Красноярск', 'Пермь', 'Воронеж', 'Волгоград'
                     ]
    city = arg.split(' , ')[0]
    if (city == 'Москва') or (city == 'Санкт-Петербург'):
        return city
    elif city in million_cities:
        return 'город миллионник'
    else:
        return 'другие'
    
def get_ready_to_move(arg):
    if ('не готов к переезду' in arg) or ('не готова к переезду' in arg):
        return False
    elif 'хочу' in arg:
        return True
    else:
        return True
    
def get_ready_for_bisiness_trips(arg):
    if ('командировка' in arg):
        if ('не готов к командировкам' in arg) or('не готова к командировкам' in arg):
            return False
        else: 
            
            return True
    else:
        return False
    
hh_data_copy['Город'] = hh_data_copy['Город, переезд, командировки'].apply(get_city)
hh_data_copy['Готовность к переезду'] = hh_data_copy['Город, переезд, командировки'].apply(get_ready_to_move)
hh_data_copy['Готовность к командировкам'] = hh_data_copy['Город, переезд, командировки'].apply(get_ready_for_bisiness_trips)
hh_data_copy = hh_data_copy.drop('Город, переезд, командировки', axis=1)
print(round(hh_data_copy['Город'].value_counts(normalize=True)['Санкт-Петербург'] * 100)) 
print(round(hh_data_copy[
    hh_data_copy['Готовность к переезду'] & hh_data_copy['Готовность к командировкам']
].shape[0] / hh_data_copy.shape[0] *100))

KeyError: 'Город, переезд, командировки'

Рассмотрим поближе признаки «Занятость» и «График».

Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удалённая работа, вахтовый метод).

На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:

полная занятость, частичная занятость;
частичная занятость, проектная работа, волонтерство;
полный день, удалённая работа;
вахтовый метод, гибкий график, удалённая работа, полная занятость.
Такой вариант признаков имеет множество различных комбинаций, а значит, множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-«мигалки» для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе — False.

Такой метод преобразования категориальных признаков называется One Hot Encoding, его схема представлена на рисунке ниже:

Выполните данное преобразование для признаков «Занятость» и «График», ответьте на контрольные вопросы, после чего удалите их из таблицы.

In [21]:
# Список уникальных категорий для «Занятость» и «График»
employment_categories = ['полная занятость', 'частичная занятость', 'проектная работа', 'волонтерство', 'стажировка']
schedule_categories = ['полный день', 'сменный график', 'гибкий график', 'удалённая работа', 'вахтовый метод']

# Функция для создания признаков-«мигалок»
def create_ohe_columns(df, column, categories):
    for category in categories:
        df[f'{column}_{category}'] = df[column].apply(lambda x: category in x)
    return df

# Применяем One Hot Encoding к столбцу «Занятость»
hh_data_copy = create_ohe_columns(hh_data_copy, 'Занятость', employment_categories)

# Применяем One Hot Encoding к столбцу «График»
hh_data_copy = create_ohe_columns(hh_data_copy, 'График', schedule_categories)

# Удаляем исходные столбцы «Занятость» и «График»
hh_data_copy.drop(columns=['Занятость', 'График'], inplace=True)

# Проверяем результат
hh_data_copy.head()

,ЗП,Ищет работу на должность:,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,...,Занятость_полная занятость,Занятость_частичная занятость,Занятость_проектная работа,Занятость_волонтерство,Занятость_стажировка,График_полный день,График_сменный график,График_гибкий график,График_удалённая работа,График_вахтовый метод
0,29000 руб.,Системный администратор,Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее,Мужчина,39 лет,...,True,True,True,False,False,True,True,True,False,True
1,40000 руб.,Технический писатель,Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",12.04.2019 8:42,Не указано,высшее,Мужчина,60 лет,...,True,True,True,False,False,True,True,True,False,False
2,20000 руб.,Оператор,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,16.04.2019 8:35,Не указано,среднее специальное,Женщина,36 лет,...,True,False,False,False,False,True,False,False,False,False
3,100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,08.04.2019 14:23,Не указано,высшее,Мужчина,38 лет,...,True,True,True,False,False,False,False,True,False,False
4,140000 руб.,Региональный менеджер по продажам,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,22.04.2019 10:32,Не указано,высшее,Женщина,26 лет,...,True,False,False,False,False,True,False,False,False,False

In [22]:
# Подсчитываем количество людей, которые ищут и проектную работу, и волонтерство
project_and_volunteer = hh_data_copy[
    (hh_data_copy['Занятость_проектная работа'] == True) &
    (hh_data_copy['Занятость_волонтерство'] == True)
].shape[0]

# Выводим результат
print(f"Количество людей, ищущих проектную работу и волонтерство: {project_and_volunteer}")

Количество людей, ищущих проектную работу и волонтерство: 436

In [23]:
# Подсчитываем количество людей, которые хотят работать вахтовым методом и с гибким графиком
shift_and_flexible = hh_data_copy[
    (hh_data_copy['График_вахтовый метод'] == True) &
    (hh_data_copy['График_гибкий график'] == True)
].shape[0]

# Выводим результат
print(f"Количество людей, которые хотят работать вахтовым методом и с гибким графиком: {shift_and_flexible}")

Количество людей, которые хотят работать вахтовым методом и с гибким графиком: 2311

Наконец, мы добрались до самого главного — признака заработной платы «ЗП». 

В чём наша проблема? — В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он хотел бы её получать, например:

30 000 руб.;
50 000 грн.;
550 USD.
Нам бы хотелось видеть заработную плату в единой валюте, например в рублях. Возникает вопрос: а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации: от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако в рамках нашего проекта эти темы мы рассматривать не будем.

Поэтому просто обратимся к профильным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MFD.RU: данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019: скачать её вы можете здесь.

Создайте новый DataFrame из скачанного файла. В полученной таблице нас будут интересовать столбцы:

currency — наименование валюты в ISO-кодировке;
date — дата;
proportion — пропорция;
close — цена закрытия (последний зафиксированный курс валюты на указанный день).
Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в файле с курсами валют.

Пропорция — это число, отражающее, скольким единицам валюты соответствует курс в таблице с курсами. Например для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен: 17.197 / 100 = 0.17197 руб. за 1 тенге.

Воспользуйтесь этой информацией в ваших преобразованиях.

Наименование валюты в данных	Наименование валюты в ISO-кодировке	Пропорция	Расшифровка
грн	UAH	10	гривна
USD	USD	1	доллар
EUR	EUR	1	евро
белруб	BYN	1	белорусский рубль
KGS	KGS	10	киргизский сом
сум	UZS	10 000	узбекский сум
AZN	AZN	1	азербайджанский манат
KZT	KZT	100	казахстанский тенге
Осталось только понять, откуда брать дату, по которой определяется курс. А вот же она — в признаке «Обновление резюме» содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней мы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак «ЗП (руб)» — заработная плата в рублях.

Итак, давайте обсудим возможный алгоритм преобразования.

Подсказки
1
Обновить признак "Обновление резюме" из таблицы с резюме, переведя его в формат datetime и выделив из него дату. То есть в дате обновления резюме мы намеренно отсекаем время, оставляя только дату выставления резюме. В тот же формат привести признак date из таблицы с валютами. Обратите внимание на формат даты в исходных столбцах (день-месяц-год), учтите этот факт при преобразовании.

2
Выделить из столбца «ЗП» сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно таблице выше.

3
Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе).

4
Умножить сумму желаемой заработной платы на присоединённый курс валюты (close) и разделить на пропорцию. Обратите внимание на пропуски после объединения в этих столбцах. Результат занести в новый столбец «ЗП (руб)».

Удалите исходный столбец заработной платы «ЗП» и все промежуточные столбцы, если вы их создавали.

In [49]:
# Преобразуем столбец «Обновление резюме» в datetime
hh_data_copy['Обновление резюме'] = pd.to_datetime(hh_data_copy['Обновление резюме'], format='%d.%m.%Y %H:%M')

# Извлекаем только дату
hh_data_copy['Дата обновления'] = hh_data_copy['Обновление резюме'].dt.date

In [50]:
# Загружаем данные о курсах валют
currency_data = pd.read_csv('data/currency_rates.csv')

# Преобразуем столбец date в datetime с правильным форматом
currency_data['date'] = pd.to_datetime(currency_data['date'], format='%d/%m/%y')

# Оставляем только нужные столбцы
currency_data = currency_data[['currency', 'date', 'proportion', 'close']]

In [67]:
# создадим таблицу соответствия валют по заданию
currency_mapping = {
    'грн': {'iso': 'UAH', 'proportion': 10},
    'USD': {'iso': 'USD', 'proportion': 1},
    'EUR': {'iso': 'EUR', 'proportion': 1},
    'белруб': {'iso': 'BYN', 'proportion': 30},
    'KGS': {'iso': 'KGS', 'proportion': 10},
    'сум': {'iso': 'UZS', 'proportion': 10000},
    'AZN': {'iso': 'AZN', 'proportion': 1},
    'KZT': {'iso': 'KZT', 'proportion': 100},
    'руб': {'iso': 'RUB', 'proportion': 1}  # Добавляем рубль
}

# Разделяем столбец ЗП» на сумму и валюту
hh_data_copy[['ЗП сумма', 'ЗП валюта']] = hh_data_copy['ЗП'].str.split(n=1, expand=True)
# Удаляем точку из валюты
hh_data_copy['ЗП валюта'] = hh_data_copy['ЗП валюта'].str.replace('.', '')
# Преобразуем в float
hh_data_copy['ЗП сумма'] = hh_data_copy['ЗП сумма'].str.replace(' ', '').astype(float)
hh_data_copy.head(32)

,ЗП,Ищет работу на должность:,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,...,Занятость_волонтерство,Занятость_стажировка,График_полный день,График_сменный график,График_гибкий график,График_удалённая работа,График_вахтовый метод,Дата обновления,ЗП сумма,ЗП валюта
0,29000 руб.,Системный администратор,Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,2019-04-16 15:59:00,Имеется собственный автомобиль,неоконченное высшее,Мужчина,39 лет,...,False,False,True,True,True,False,True,2019-04-16,29000.0,руб
1,40000 руб.,Технический писатель,Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",2019-04-12 08:42:00,Не указано,высшее,Мужчина,60 лет,...,False,False,True,True,True,False,False,2019-04-12,40000.0,руб
2,20000 руб.,Оператор,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,2019-04-16 08:35:00,Не указано,среднее специальное,Женщина,36 лет,...,False,False,True,False,False,False,False,2019-04-16,20000.0,руб
3,100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,2019-04-08 14:23:00,Не указано,высшее,Мужчина,38 лет,...,False,False,False,False,True,False,False,2019-04-08,100000.0,руб
4,140000 руб.,Региональный менеджер по продажам,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,2019-04-22 10:32:00,Не указано,высшее,Женщина,26 лет,...,False,False,True,False,False,False,False,2019-04-22,140000.0,руб
5,25000 руб.,Технический специалист,Опыт работы 9 лет 9 месяцев Технический специ...,Комбинат хлебопродуктов Старооскольский,Слесарь КИПиА,2019-04-22 15:59:00,Имеется собственный автомобиль,неоконченное высшее,Мужчина,29 лет,...,False,False,True,True,False,False,False,2019-04-22,25000.0,руб
6,250000 руб.,Руководитель ИТ-проектов,Опыт работы 22 года 9 месяцев Руководитель ИТ...,"СИБИНТЕК, ООО ИК",Менеджер (Руководитель ИТ-проектов),2019-04-25 22:48:00,Не указано,высшее,Мужчина,46 лет,...,False,False,True,False,False,False,False,2019-04-25,250000.0,руб
7,70000 руб.,Инженер АСУ ТП,Опыт работы 3 года 11 месяцев Декабрь 2016 — ...,ФМ-инжиниринг,Инженер АСУ ТП,2019-05-07 17:59:00,Не указано,высшее,Мужчина,29 лет,...,False,False,True,False,False,False,False,2019-05-07,70000.0,руб
8,65000 руб.,Ревизор,Опыт работы 8 лет 9 месяцев Декабрь 2016 — по...,ФГБУ РСВО,Старший специалист,2019-04-11 11:08:00,Имеется собственный автомобиль,неоконченное высшее,Мужчина,29 лет,...,False,False,True,False,False,False,False,2019-04-11,65000.0,руб
9,55000 руб.,"Менеджер по работе с клиентами, Pre-sale менед...",Опыт работы 16 лет 6 месяцев Июнь 2018 — по н...,"ООО ""Мираском""",Специалист отдела ИТ,2019-04-19 11:39:00,Имеется собственный автомобиль,высшее,Мужчина,34 года,...,False,False,True,False,False,False,False,2019-04-19,55000.0,руб
10,55000 руб.,Менеджер / оператор интернет-магазина,Опыт работы 11 лет 5 месяцев Январь 2008 — по...,Сеть свадебных салон Primavera,Администратор интернет-магазина и салона,2019-04-11 10:56:00,Не указано,среднее специальное,Женщина,35 лет,...,False,False,True,False,False,False,False,2019-04-11,55000.0,руб
11,80000 руб.,Технический писатель,Опыт работы 42 года 6 месяцев Технический пис...,"ООО ""В-класс""",Ведущий специалист научно-технического отдела,2019-04-26 14:37:00,Не указано,высшее,Мужчина,59 лет,...,False,False,True,False,False,False,False,2019-04-26,80000.0,руб
12,40000 руб.,Инженер-программист,Опыт работы 13 лет 6 месяцев Инженер-программ...,Эльдорадо (Россия),Продавец-консультант,2019-04-26 05:57:00,Не указано,среднее специальное,Мужчина,39 лет,...,False,False,True,True,False,False,False,2019-04-26,40000.0,руб
13,90000 руб.,SMM-менеджер/ SEO/ creator,Опыт работы 6 лет 11 месяцев Февраль 2017 — п...,ГРУППА ИМА,SMM-менеджер/ SEO,2019-04-16 11:27:00,Не указано,высшее,Женщина,27 лет,...,False,False,False,False,False,False,False,2019-04-16,90000.0,руб
14,25000 руб.,Менеджер проекта,Опыт работы 1 год 5 месяцев Октябрь 2017 — Фе...,Ays отель,Старший официант,2019-04-18 19:05:00,Не указано,среднее специальное,Женщина,21 год,...,False,False,True,False,False,False,False,2019-04-18,25000.0,руб
15,23000 руб.,Специалист,Опыт работы 3 года 10 месяцев Специалист 23 0...,Динамика 76,Контент-менеджер,2019-04-26 09:13:00,Не указано,высшее,Мужчина,31 год,...,False,False,True,True,True,False,False,2019-04-26,23000.0,руб
16,120000 руб.,"Дизайнер продукта, UX/UI",Опыт работы 9 лет 1 месяц Апрель 2016 — по на...,Zenon,"Дизайнер продукта, UX/UI дизайнер",2019-04-12 15:05:00,Не указано,высшее,Мужчина,29 лет,...,False,False,True,False,False,False,False,2019-04-12,120000.0,руб
17,30000 руб.,Инженер Отдела IT,Опыт работы 15 лет 9 месяцев Февраль 2018 — п...,Великолукский мясокомбинат,Дежурный IT-инженер,2019-04-11 07:40:00,Не указано,неоконченное высшее,Мужчина,37 лет,...,False,False,True,False,False,False,False,2019-04-11,30000.0,руб
18,260000 руб.,Ведущий программист 1C / Руководитель,Опыт работы 9 лет 6 месяцев Ведущий программи...,Сантехника-онлайн.Ру,Ведущий программист 1C,2019-04-26 11:42:00,Имеется собственный автомобиль,высшее,Мужчина,30 лет,...,False,False,True,False,False,False,False,2019-04-26,260000.0,руб
19,55000 руб.,Менеджер интернет-магазина,Опыт работы 11 лет 11 месяцев Март 2018 — по ...,"Интернет-магазин ""Доктор Кастом Ру"" (ИП Смолин...",Руководитель отдела веб-продаж и сервиса,2019-05-07 15:37:00,Не указано,неоконченное высшее,Мужчина,38 лет,...,False,False,True,False,False,False,False,2019-05-07,55000.0,руб
20,80000 руб.,Сетевой инженер / Системный администратор,Опыт работы 4 года 11 месяцев Май 2018 — по н...,АйТи-Сервис,Системный администратор,2019-04-18 16:46:00,Имеется собственный автомобиль,высшее,Мужчина,31 год,...,False,False,True,True,True,False,False,2019-04-18,80000.0,руб
21,70000 руб.,"Программист C++, Web-программист, разработчик ...",Опыт работы 5 лет 8 месяцев Март 2019 — по на...,Удаленная работа,Web-программист,2019-04-17 16:49:00,Имеется собственный автомобиль,высшее,Мужчина,27 лет,...,False,False,True,True,True,False,False,2019-04-17,70000.0,руб
22,70000 руб.,Технический специалист,Опыт работы 13 лет 4 месяца Июнь 2017 — по на...,"АО ""Нокиа Солюшнз энд Нетворкс"" (АО ""НСН"")",Старший инженер по эксплуатации мобильной сети,2019-04-10 09:26:00,Не указано,высшее,Мужчина,36 лет,...,False,False,True,True,True,False,False,2019-04-10,70000.0,руб
23,60000 руб.,Golang разработчик,Опыт работы 11 лет 6 месяцев Golang разработч...,Eastwood,Программист Python,2019-04-25 14:50:00,Не указано,высшее,Мужчина,33 года,...,False,False,True,False,True,False,False,2019-04-25,60000.0,руб
24,61000 руб.,"начальник отдела, главный специалист, аудитор,...",Опыт работы 12 лет 3 месяца Апрель 2017 — по ...,Банк,главный экономист - аналитик Отдела методологи...,2019-05-07 13:16:00,Не указано,высшее,Мужчина,34 года,...,False,False,True,False,False,False,False,2019-05-07,61000.0,руб
25,20000 руб.,"секретарь,администратор,помощник руководителя.",Опыт работы 9 лет 3 месяца Март 2010 — по нас...,"Ангам,Универмаг Зум.",Продавец-консультант,2019-04-14 16:23:00,Не указано,высшее,Женщина,27 лет,...,False,False,True,False,False,False,False,2019-04-14,20000.0,руб
26,80000 руб.,"pre-sale инженер, pre-sale менеджер",Опыт работы 19 лет 9 месяцев Сентябрь 2017 — ...,"Унилинк, ООО",Руководитель группы по работе с операторами и ...,2019-05-13 16:03:00,Не указано,высшее,Женщина,42 года,...,False,False,True,False,True,False,False,2019-05-13,80000.0,руб
27,250000 руб.,"Руководитель ИТ-отдела, руководитель отдела си...",Опыт работы 14 лет 10 месяцев Февраль 2014 — ...,"Sovcomflot, PAO",Senior specialist,2019-05-07 10:45:00,Не указано,высшее,Мужчина,36 лет,...,False,False,True,False,False,False,False,2019-05-07,250000.0,руб
28,45000 руб.,Гейм-дизайнер,Опыт работы 8 лет 9 месяцев Гейм-дизайнер 45 ...,Глобэкс АйТи,Специалист технической поддержки,2019-04-22 01:39:00,Не указано,неоконченное высшее,Женщина,32 года,...,False,True,True,False,True,False,False,2019-04-22,45000.0,руб
29,50000 руб.,Системный администратор,Опыт работы 9 лет 4 месяца Системный админист...,"ООО ""Дилижанс""",Системный администратор,2019-04-22 13:51:00,Не указано,высшее,Мужчина,32 года,...,False,False,True,False,False,False,False,2019-04-22,50000.0,руб
30,3000 бел.руб.,Engineer,Опыт работы 8 лет 2 месяца Engineer 3 000 бел...,Outsourcing,Data Engineer,2019-04-26 12:44:00,Не указано,высшее,Женщина,31 год,...,False,False,True,False,False,False,False,2019-04-26,3000.0,белруб
31,170000 руб.,Системный аналитик,Опыт работы 4 года 11 месяцев Июль 2014 — по ...,Ингосстрах,Системный аналитик,2019-05-14 09:11:00,Не указано,высшее,Женщина,33 года,...,False,False,True,False,True,False,False,2019-05-14,170000.0,руб

In [74]:
# Используем словарь currency_mapping для преобразования названий валют в ISO-коды
hh_data_copy['ЗП валюта'] = hh_data_copy['ЗП валюта'].map(
    lambda x: currency_mapping[x]['iso'] if x in currency_mapping else None
)

# Проверяем результат
print("Уникальные значения в 'ЗП валюта' после преобразования:")
print(hh_data_copy['ЗП валюта'].unique())

# Преобразуем столбец «Дата обновления» в datetime
hh_data_copy['Дата обновления'] = pd.to_datetime(hh_data_copy['Дата обновления'])

# Объединяем данные с курсами валют
merged_data = pd.merge(
    hh_data_copy,
    currency_data,
    left_on=['Дата обновления', 'ЗП валюта'],
    right_on=['date', 'currency'],
    how='left'
)

# Заполняем proportion и close для рубля (RUB)
merged_data.loc[merged_data['ЗП валюта'] == 'RUB', 'close'] = 1
merged_data.loc[merged_data['ЗП валюта'] == 'RUB', 'proportion'] = 1.0

# Проверяем результат
#print(merged_data[['ЗП валюта', 'proportion', 'close']].head(32))

merged_data.head(32)

Уникальные значения в 'ЗП валюта' после преобразования:
[None 'KZT' 'EUR' 'USD' 'KGS' 'AZN']

,ЗП,Ищет работу на должность:,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,...,График_гибкий график,График_удалённая работа,График_вахтовый метод,Дата обновления,ЗП сумма,ЗП валюта,currency,date,proportion,close
0,29000 руб.,Системный администратор,Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,2019-04-16 15:59:00,Имеется собственный автомобиль,неоконченное высшее,Мужчина,39 лет,...,True,False,True,2019-04-16,29000.0,None,NaN,NaT,NaN,NaN
1,40000 руб.,Технический писатель,Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",2019-04-12 08:42:00,Не указано,высшее,Мужчина,60 лет,...,True,False,False,2019-04-12,40000.0,None,NaN,NaT,NaN,NaN
2,20000 руб.,Оператор,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,2019-04-16 08:35:00,Не указано,среднее специальное,Женщина,36 лет,...,False,False,False,2019-04-16,20000.0,None,NaN,NaT,NaN,NaN
3,100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,2019-04-08 14:23:00,Не указано,высшее,Мужчина,38 лет,...,True,False,False,2019-04-08,100000.0,None,NaN,NaT,NaN,NaN
4,140000 руб.,Региональный менеджер по продажам,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,2019-04-22 10:32:00,Не указано,высшее,Женщина,26 лет,...,False,False,False,2019-04-22,140000.0,None,NaN,NaT,NaN,NaN
5,25000 руб.,Технический специалист,Опыт работы 9 лет 9 месяцев Технический специ...,Комбинат хлебопродуктов Старооскольский,Слесарь КИПиА,2019-04-22 15:59:00,Имеется собственный автомобиль,неоконченное высшее,Мужчина,29 лет,...,False,False,False,2019-04-22,25000.0,None,NaN,NaT,NaN,NaN
6,250000 руб.,Руководитель ИТ-проектов,Опыт работы 22 года 9 месяцев Руководитель ИТ...,"СИБИНТЕК, ООО ИК",Менеджер (Руководитель ИТ-проектов),2019-04-25 22:48:00,Не указано,высшее,Мужчина,46 лет,...,False,False,False,2019-04-25,250000.0,None,NaN,NaT,NaN,NaN
7,70000 руб.,Инженер АСУ ТП,Опыт работы 3 года 11 месяцев Декабрь 2016 — ...,ФМ-инжиниринг,Инженер АСУ ТП,2019-05-07 17:59:00,Не указано,высшее,Мужчина,29 лет,...,False,False,False,2019-05-07,70000.0,None,NaN,NaT,NaN,NaN
8,65000 руб.,Ревизор,Опыт работы 8 лет 9 месяцев Декабрь 2016 — по...,ФГБУ РСВО,Старший специалист,2019-04-11 11:08:00,Имеется собственный автомобиль,неоконченное высшее,Мужчина,29 лет,...,False,False,False,2019-04-11,65000.0,None,NaN,NaT,NaN,NaN
9,55000 руб.,"Менеджер по работе с клиентами, Pre-sale менед...",Опыт работы 16 лет 6 месяцев Июнь 2018 — по н...,"ООО ""Мираском""",Специалист отдела ИТ,2019-04-19 11:39:00,Имеется собственный автомобиль,высшее,Мужчина,34 года,...,False,False,False,2019-04-19,55000.0,None,NaN,NaT,NaN,NaN
10,55000 руб.,Менеджер / оператор интернет-магазина,Опыт работы 11 лет 5 месяцев Январь 2008 — по...,Сеть свадебных салон Primavera,Администратор интернет-магазина и салона,2019-04-11 10:56:00,Не указано,среднее специальное,Женщина,35 лет,...,False,False,False,2019-04-11,55000.0,None,NaN,NaT,NaN,NaN
11,80000 руб.,Технический писатель,Опыт работы 42 года 6 месяцев Технический пис...,"ООО ""В-класс""",Ведущий специалист научно-технического отдела,2019-04-26 14:37:00,Не указано,высшее,Мужчина,59 лет,...,False,False,False,2019-04-26,80000.0,None,NaN,NaT,NaN,NaN
12,40000 руб.,Инженер-программист,Опыт работы 13 лет 6 месяцев Инженер-программ...,Эльдорадо (Россия),Продавец-консультант,2019-04-26 05:57:00,Не указано,среднее специальное,Мужчина,39 лет,...,False,False,False,2019-04-26,40000.0,None,NaN,NaT,NaN,NaN
13,90000 руб.,SMM-менеджер/ SEO/ creator,Опыт работы 6 лет 11 месяцев Февраль 2017 — п...,ГРУППА ИМА,SMM-менеджер/ SEO,2019-04-16 11:27:00,Не указано,высшее,Женщина,27 лет,...,False,False,False,2019-04-16,90000.0,None,NaN,NaT,NaN,NaN
14,25000 руб.,Менеджер проекта,Опыт работы 1 год 5 месяцев Октябрь 2017 — Фе...,Ays отель,Старший официант,2019-04-18 19:05:00,Не указано,среднее специальное,Женщина,21 год,...,False,False,False,2019-04-18,25000.0,None,NaN,NaT,NaN,NaN
15,23000 руб.,Специалист,Опыт работы 3 года 10 месяцев Специалист 23 0...,Динамика 76,Контент-менеджер,2019-04-26 09:13:00,Не указано,высшее,Мужчина,31 год,...,True,False,False,2019-04-26,23000.0,None,NaN,NaT,NaN,NaN
16,120000 руб.,"Дизайнер продукта, UX/UI",Опыт работы 9 лет 1 месяц Апрель 2016 — по на...,Zenon,"Дизайнер продукта, UX/UI дизайнер",2019-04-12 15:05:00,Не указано,высшее,Мужчина,29 лет,...,False,False,False,2019-04-12,120000.0,None,NaN,NaT,NaN,NaN
17,30000 руб.,Инженер Отдела IT,Опыт работы 15 лет 9 месяцев Февраль 2018 — п...,Великолукский мясокомбинат,Дежурный IT-инженер,2019-04-11 07:40:00,Не указано,неоконченное высшее,Мужчина,37 лет,...,False,False,False,2019-04-11,30000.0,None,NaN,NaT,NaN,NaN
18,260000 руб.,Ведущий программист 1C / Руководитель,Опыт работы 9 лет 6 месяцев Ведущий программи...,Сантехника-онлайн.Ру,Ведущий программист 1C,2019-04-26 11:42:00,Имеется собственный автомобиль,высшее,Мужчина,30 лет,...,False,False,False,2019-04-26,260000.0,None,NaN,NaT,NaN,NaN
19,55000 руб.,Менеджер интернет-магазина,Опыт работы 11 лет 11 месяцев Март 2018 — по ...,"Интернет-магазин ""Доктор Кастом Ру"" (ИП Смолин...",Руководитель отдела веб-продаж и сервиса,2019-05-07 15:37:00,Не указано,неоконченное высшее,Мужчина,38 лет,...,False,False,False,2019-05-07,55000.0,None,NaN,NaT,NaN,NaN
20,80000 руб.,Сетевой инженер / Системный администратор,Опыт работы 4 года 11 месяцев Май 2018 — по н...,АйТи-Сервис,Системный администратор,2019-04-18 16:46:00,Имеется собственный автомобиль,высшее,Мужчина,31 год,...,True,False,False,2019-04-18,80000.0,None,NaN,NaT,NaN,NaN
21,70000 руб.,"Программист C++, Web-программист, разработчик ...",Опыт работы 5 лет 8 месяцев Март 2019 — по на...,Удаленная работа,Web-программист,2019-04-17 16:49:00,Имеется собственный автомобиль,высшее,Мужчина,27 лет,...,True,False,False,2019-04-17,70000.0,None,NaN,NaT,NaN,NaN
22,70000 руб.,Технический специалист,Опыт работы 13 лет 4 месяца Июнь 2017 — по на...,"АО ""Нокиа Солюшнз энд Нетворкс"" (АО ""НСН"")",Старший инженер по эксплуатации мобильной сети,2019-04-10 09:26:00,Не указано,высшее,Мужчина,36 лет,...,True,False,False,2019-04-10,70000.0,None,NaN,NaT,NaN,NaN
23,60000 руб.,Golang разработчик,Опыт работы 11 лет 6 месяцев Golang разработч...,Eastwood,Программист Python,2019-04-25 14:50:00,Не указано,высшее,Мужчина,33 года,...,True,False,False,2019-04-25,60000.0,None,NaN,NaT,NaN,NaN
24,61000 руб.,"начальник отдела, главный специалист, аудитор,...",Опыт работы 12 лет 3 месяца Апрель 2017 — по ...,Банк,главный экономист - аналитик Отдела методологи...,2019-05-07 13:16:00,Не указано,высшее,Мужчина,34 года,...,False,False,False,2019-05-07,61000.0,None,NaN,NaT,NaN,NaN
25,20000 руб.,"секретарь,администратор,помощник руководителя.",Опыт работы 9 лет 3 месяца Март 2010 — по нас...,"Ангам,Универмаг Зум.",Продавец-консультант,2019-04-14 16:23:00,Не указано,высшее,Женщина,27 лет,...,False,False,False,2019-04-14,20000.0,None,NaN,NaT,NaN,NaN
26,80000 руб.,"pre-sale инженер, pre-sale менеджер",Опыт работы 19 лет 9 месяцев Сентябрь 2017 — ...,"Унилинк, ООО",Руководитель группы по работе с операторами и ...,2019-05-13 16:03:00,Не указано,высшее,Женщина,42 года,...,True,False,False,2019-05-13,80000.0,None,NaN,NaT,NaN,NaN
27,250000 руб.,"Руководитель ИТ-отдела, руководитель отдела си...",Опыт работы 14 лет 10 месяцев Февраль 2014 — ...,"Sovcomflot, PAO",Senior specialist,2019-05-07 10:45:00,Не указано,высшее,Мужчина,36 лет,...,False,False,False,2019-05-07,250000.0,None,NaN,NaT,NaN,NaN
28,45000 руб.,Гейм-дизайнер,Опыт работы 8 лет 9 месяцев Гейм-дизайнер 45 ...,Глобэкс АйТи,Специалист технической поддержки,2019-04-22 01:39:00,Не указано,неоконченное высшее,Женщина,32 года,...,True,False,False,2019-04-22,45000.0,None,NaN,NaT,NaN,NaN
29,50000 руб.,Системный администратор,Опыт работы 9 лет 4 месяца Системный админист...,"ООО ""Дилижанс""",Системный администратор,2019-04-22 13:51:00,Не указано,высшее,Мужчина,32 года,...,False,False,False,2019-04-22,50000.0,None,NaN,NaT,NaN,NaN
30,3000 бел.руб.,Engineer,Опыт работы 8 лет 2 месяца Engineer 3 000 бел...,Outsourcing,Data Engineer,2019-04-26 12:44:00,Не указано,высшее,Женщина,31 год,...,False,False,False,2019-04-26,3000.0,None,NaN,NaT,NaN,NaN
31,170000 руб.,Системный аналитик,Опыт работы 4 года 11 месяцев Июль 2014 — по ...,Ингосстрах,Системный аналитик,2019-05-14 09:11:00,Не указано,высшее,Женщина,33 года,...,True,False,False,2019-05-14,170000.0,None,NaN,NaT,NaN,NaN

In [ ]:
# Рассчитываем ЗП в рублях
merged_data['ЗП (руб)'] = (merged_data['ЗП сумма'] * merged_data['close']) / merged_data['proportion']
merged_data['ЗП (руб)'] = merged_data['ЗП (руб)'].fillna(merged_data['ЗП сумма'])

# Удаляем лишние столбцы
merged_data.drop(
    columns=['ЗП', 'ЗП сумма', 'ЗП валюта', 'currency', 'date', 'proportion', 'close'],
    inplace=True
)

# Проверяем результат
# Пример для поиска белруб
merged_data.head(32)

In [76]:
print(f"Медианная заработная плата: {round(merged_data['ЗП (руб)'].median() / 1000)} тысяч рублей")

Медианная заработная плата: 58 тысяч рублей

Медианная заработная плата: 58 тысяч рублей